// Deadlines imported from the SurreyLearn calendar feed on 4 Oct 2026.
window.SEED_ITEMS = [
 {
  "id": "eco-lecture-w1",
  "title": "Lecture, week 1",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-09-29T16:00:00+01:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w1",
  "title": "Week 1 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-10-01T17:00:00+01:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Core textbook (Begg et al, Economics) Chapters 1-2 E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w2",
  "title": "Lecture, week 2",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-10-06T16:00:00+01:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps1",
  "title": "Tutorial problem set 1",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-10-07T23:59:59+01:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/content/300078/viewContent/3753997/View",
  "notes": "Due before your seminar. Solutions are released a couple of days later.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w2",
  "title": "Seminar, week 2",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-10-08T09:00:00+01:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w2",
  "title": "Week 2 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-10-08T17:00:00+01:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Core textbook (Begg et al, Economics) Chapter 3 E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w3",
  "title": "Lecture, week 3",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-10-13T16:00:00+01:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w3",
  "title": "Week 3 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-10-14T17:00:00+01:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Core textbook (Begg et al, Economics) Chapter 4 E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps2",
  "title": "Tutorial problem set 2",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-10-14T23:59:59+01:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/content/300078/viewContent/3753999/View",
  "notes": "Due before your seminar. Solutions are released a couple of days later.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w3",
  "title": "Seminar, week 3",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-10-15T09:00:00+01:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-3-practice-questions-elasticities",
  "title": "Week 3 practice questions (elasticities)",
  "module": "ECO1014",
  "kind": "practice",
  "due": "2026-10-15T23:59:00+01:00",
  "hours": 1,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476007/detailsview?ou=300078#476007",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-quiz-topics-1-to-2",
  "title": "Weekly quiz (topics 1 to 2)",
  "module": "ECO1014",
  "kind": "quiz",
  "due": "2026-10-19T18:00:00+01:00",
  "hours": 1.5,
  "done": false,
  "url": "",
  "notes": "Open Monday 14:00 to 18:00.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w4",
  "title": "Lecture, week 4",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-10-20T16:00:00+01:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w4",
  "title": "Week 4 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-10-21T17:00:00+01:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Core textbook (Begg et al, Economics) Chapter 5 E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps3",
  "title": "Tutorial problem set 3",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-10-21T23:59:59+01:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/content/300078/viewContent/3754001/View",
  "notes": "Due before your seminar. Solutions are released a couple of days later.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w4",
  "title": "Seminar, week 4",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-10-22T09:00:00+01:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-4-practice-questions",
  "title": "Week 4 practice questions",
  "module": "ECO1014",
  "kind": "practice",
  "due": "2026-10-22T23:59:00+01:00",
  "hours": 1,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476032/detailsview?ou=300078#476032",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-quiz-topics-1-to-3",
  "title": "Weekly quiz (topics 1 to 3)",
  "module": "ECO1014",
  "kind": "quiz",
  "due": "2026-10-26T18:00:00+00:00",
  "hours": 1.5,
  "done": false,
  "url": "",
  "notes": "Open Monday 14:00 to 18:00.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-5-utility-maximization-assignment",
  "title": "Week 5 utility maximisation assignment",
  "module": "ECO1014",
  "kind": "assignment",
  "due": "2026-10-26T23:59:00+00:00",
  "hours": 3,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476019/detailsview?ou=300078#476019",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w5",
  "title": "Lecture, week 5",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-10-27T16:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w5",
  "title": "Week 5 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-10-28T17:00:00+00:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Core textbook (Begg et al, Economics) Chapter 5 E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps4",
  "title": "Tutorial problem set 4",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-10-28T23:59:59+00:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/content/300078/viewContent/3754002/View",
  "notes": "Due before your seminar. Solutions are released a couple of days later.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w5",
  "title": "Seminar, week 5",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-10-29T09:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-5-practice-questions",
  "title": "Week 5 practice questions",
  "module": "ECO1014",
  "kind": "practice",
  "due": "2026-10-29T23:59:00+00:00",
  "hours": 1,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476022/detailsview?ou=300078#476022",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-quiz-topics-1-to-5",
  "title": "Weekly quiz (topics 1 to 5)",
  "module": "ECO1014",
  "kind": "quiz",
  "due": "2026-11-02T18:00:00+00:00",
  "hours": 1.5,
  "done": false,
  "url": "",
  "notes": "Open Monday 14:00 to 18:00.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-6-application-based-activity",
  "title": "Week 6 application activity",
  "module": "ECO1014",
  "kind": "assignment",
  "due": "2026-11-02T23:59:00+00:00",
  "hours": 1.5,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476012/detailsview?ou=300078#476012",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w6",
  "title": "Lecture, week 6",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-11-03T16:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w6",
  "title": "Week 6 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-11-04T17:00:00+00:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Core textbook (Begg et al, Economics) Chapter 17 and 19 (2020 version) or chapters 15-16 (2017 version) E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps5",
  "title": "Tutorial problem set 5",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-11-04T23:59:59+00:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/content/300078/viewContent/3754004/View",
  "notes": "Due before your seminar. Solutions are released a couple of days later.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-6-practice-questions",
  "title": "Week 6 practice questions",
  "module": "ECO1014",
  "kind": "practice",
  "due": "2026-11-05T23:59:00+00:00",
  "hours": 1,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476010/detailsview?ou=300078#476010",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w6",
  "title": "Seminar, week 6",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-11-06T09:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w7",
  "title": "Lecture, week 7",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-11-10T16:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w7",
  "title": "Week 7 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-11-11T17:00:00+00:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Core textbook (Begg et al, Economics) Chapter 20 (2020) or 17 (2017) E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w7",
  "title": "Seminar, week 7",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-11-12T09:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-midterm",
  "title": "Midterm",
  "module": "ECO1014",
  "kind": "exam",
  "due": "2026-11-16T10:00:00+00:00",
  "hours": 8,
  "done": false,
  "url": "",
  "notes": "See your assigned time on SurreyLearn. Instructions usually come out the week before.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-7-trade-assignment",
  "title": "Week 7 trade assignment",
  "module": "ECO1014",
  "kind": "assignment",
  "due": "2026-11-16T23:59:00+00:00",
  "hours": 3,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476035/detailsview?ou=300078#476035",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-7-practice-questions",
  "title": "Week 7 practice questions",
  "module": "ECO1014",
  "kind": "practice",
  "due": "2026-11-19T23:59:00+00:00",
  "hours": 1,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476040/detailsview?ou=300078#476040",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-quiz-topic-6",
  "title": "Weekly quiz (topic 6)",
  "module": "ECO1014",
  "kind": "quiz",
  "due": "2026-11-23T18:00:00+00:00",
  "hours": 1.5,
  "done": false,
  "url": "",
  "notes": "Open Monday 14:00 to 18:00.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-8-application-based-activity",
  "title": "Week 8 application activity",
  "module": "ECO1014",
  "kind": "assignment",
  "due": "2026-11-23T23:59:00+00:00",
  "hours": 1.5,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476029/detailsview?ou=300078#476029",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w9",
  "title": "Lecture, week 9",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-11-24T16:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w9",
  "title": "Week 9 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-11-25T17:00:00+00:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/lessons/209221/topics/1866431",
  "notes": "Krugman, Obstfeld and Melitz, chapter 9. Optimal Tariffs: the Evidence. Irwin, Does Trade Promote Economic Growth? Reading list is under the week 9 topic on SurreyLearn.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps7",
  "title": "Tutorial problem set 7",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-11-25T23:59:59+00:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/content/300078/viewContent/3754042/View",
  "notes": "Due before your seminar. Solutions are released a couple of days later.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w9",
  "title": "Seminar, week 9",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-11-26T09:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-week-8-practice-questions",
  "title": "Week 8 practice questions",
  "module": "ECO1014",
  "kind": "practice",
  "due": "2026-11-26T23:59:00+00:00",
  "hours": 1,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/300078/event/476036/detailsview?ou=300078#476036",
  "notes": "",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-quiz-topics-6-to-8",
  "title": "Weekly quiz (topics 6 to 8)",
  "module": "ECO1014",
  "kind": "quiz",
  "due": "2026-11-30T18:00:00+00:00",
  "hours": 1.5,
  "done": false,
  "url": "",
  "notes": "Open Monday 14:00 to 18:00.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w10",
  "title": "Lecture, week 10",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-12-01T16:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w10",
  "title": "Week 10 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-12-02T17:00:00+00:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Core textbook (Begg et al, Economics) Chapter 21 (2020) and chapter 18 (2017 version) E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps8",
  "title": "Tutorial problem set 8",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-12-02T23:59:59+00:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/content/300078/viewContent/3754044/View",
  "notes": "Due before your seminar. Solutions are released a couple of days later.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w10",
  "title": "Seminar, week 10",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-12-03T09:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-quiz-t7-10",
  "title": "Weekly quiz (topics 7 to 10)",
  "module": "ECO1014",
  "kind": "quiz",
  "due": "2026-12-07T18:00:00+00:00",
  "hours": 1.5,
  "done": false,
  "url": "",
  "notes": "Open Monday 14:00 to 18:00.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-lecture-w11",
  "title": "Lecture, week 11",
  "module": "ECO1014",
  "kind": "lecture",
  "due": "2026-12-08T16:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Time taken from the module checklist. Check your timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-reading-w11",
  "title": "Week 11 reading",
  "module": "ECO1014",
  "kind": "reading",
  "due": "2026-12-09T17:00:00+00:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "Mankiw Macroeconomics chapter posted within Surreylearn Mankiw, chapter 10 (7th edition) or chapter 27 (6th edition). E-book: Course Materials, then Reading List.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps10",
  "title": "Tutorial problem set 10",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-12-09T17:00:00+00:00",
  "hours": 2,
  "done": false,
  "url": "",
  "notes": "From the module checklist.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "eco-ps9",
  "title": "Tutorial problem set 9",
  "module": "ECO1014",
  "kind": "problemset",
  "due": "2026-12-09T23:59:59+00:00",
  "hours": 2,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/content/300078/viewContent/3754045/View",
  "notes": "Due before your seminar. Solutions are released a couple of days later.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-seminar-w11",
  "title": "Seminar, week 11",
  "module": "ECO1014",
  "kind": "seminar",
  "due": "2026-12-10T09:00:00+00:00",
  "hours": 1,
  "done": false,
  "url": "",
  "notes": "Your section time is on your personal timetable.",
  "estimated": true,
  "source": "surreylearn"
 },
 {
  "id": "pol1028-portfolio",
  "title": "Portfolio (2,500 words)",
  "module": "POL1028",
  "kind": "assessment",
  "due": "2026-12-11T16:01:00+00:00",
  "hours": 25,
  "done": false,
  "url": "https://surreylearn.surrey.ac.uk/d2l/le/calendar/302892/event/469620/detailsview?ou=302892#469620",
  "notes": "Submit on SurreyLearn under Assignments.",
  "estimated": false,
  "source": "surreylearn"
 },
 {
  "id": "eco-revision",
  "title": "Review all topic materials",
  "module": "ECO1014",
  "kind": "revision",
  "due": "2027-02-04T23:59:00+00:00",
  "hours": 10,
  "done": false,
  "url": "",
  "notes": "SurreyLearn lists 8 topic packs due 4 Feb: demand and supply, consumer theory I and II, elasticity and taxation, actual vs potential output, money, fiscal policy and trade.",
  "estimated": false,
  "source": "surreylearn"
 }
];
